### ISSUE TITLE
Protocol.Undefined in Elixir Standard Library

### ISSUE THREAD

**Issue by StevenXL** [lpil/dogma#227] opened 2016-10-08 18:41 UTC
Hello. 

I am trying to run dogma on my code, but the process is complaining of an unimplemented protocol within what looks like the Elixir standard library. 

The [gist](https://gist.github.com/StevenXL/7e6322bd34bc0783b3327ce6a95e23ff) provides further details. 

Thank you.

**Comment by lpil** [comment] 2016-10-08 19:10
Thank you. Is the project open source? Or could you provide that one file so I can see what it looks like?

The error is coming from line 205. I think it's a call to `def` and is unquoting some value and appending `_path` ?

**Comment by lpil** [comment] 2016-10-08 19:39
Ah, dupe of #208

**Closed by lpil** 2016-10-08 19:39 UTC
