### ISSUE TITLE
taken names rule triggers inside `defimpl`

### ISSUE THREAD

**Issue by P-Seebauer** [lpil/dogma#242] opened 2017-04-15 13:26 UTC
I wrote a data structure and added an implementation for the Inspect protocol. now dogma is rasing an error, because inspect is already defined.

Minimal example:
```elixir
defmodule Foo do
  @moduledoc "Some Foo data"

  defstruct data: nil

  defimpl Inspect do
    import Inspect.Algebra
    def inspect(%Foo{data: data}, opts) do
      concat ["#Foo<", to_doc(data, opts), ">"]
    end
  end
end
```
This rasies the error `inspect is already taken and overrides the standard library [TakenName]`.

I'm not sure if `inspect` is the only keyword for that a protocol exists, but the warning is very disturbing.

**Comment by lpil** [comment] 2017-04-15 15:09
Dupe of https://github.com/lpil/dogma/issues/201

What do you think the behaviour should be?

**Closed by lpil** 2017-04-15 15:09 UTC

**Comment by P-Seebauer** [comment] 2017-04-15 22:56
Maybe it should not trigger inside `defimpl`? I'm not very accustomed with the language yet, but it seems like this is the way to use protocols, and if I want to cater one that's in Kernel, I'll get that message.

**Comment by lpil** [comment] 2017-04-16 10:22
Sounds sensible. Would you like to have a go? :)

**Comment by P-Seebauer** [comment] 2017-04-16 14:40
I'll take a look, but it might change the rule implementation fundamentally.

Also, if someone uses `@defdelegate` inside implementations (e.g. for `to_string`) it still seems odd.

```elixir
defmodule ACME.Name do
  defstruct first: "", second: ""

  def to_string %__MODULE{first: first, second: second} do
    Enum.join " ", [first, second]
  end

  defimpl String.Chars do
    defdelegate to_string(name), to: ACME.Name
  end
end
```

This would make `ACME.Name.to_string/1` accessible from outside (like it is with `Atom.to_string/1`): But inside the `ACME.Name` module, you can't use Kernel's `to_string` in bare form (and the compile fails if you try) anymore.

**Comment by lpil** [comment] 2017-04-16 14:57
It shouldn't be too hard to add a function clause that when a `defimpl` is encountered the AST is truncated to prevent any further traversal. Effectively preventing checking inside the `defimpl`. :)

**Comment by P-Seebauer** [comment] 2017-04-16 18:27
I wish I had seen this more early, now I'm deep in `Macro.traverse/4`…

Is there a reason, why the list is written by hand? It seems to me that it could be constructed automatically with something like 
```elixir
for what <- [:functions, :macros], descriptor <- Kernel.__info__(what) do 
  {name, _arity} = descriptor`
  name
end
```

**Comment by lpil** [comment] 2017-04-16 18:45
No particular reason. :)

**Comment by P-Seebauer** [comment] 2017-04-16 19:45
Would you mind if I create a pull request with my additions? It would only allow the functions to be defined that are to be implemented for a protocol.

I had to fall back to `Macro.traverse`, but I hope the code isn't that hard to digest.

**Comment by lpil** [comment] 2017-04-16 19:48
Please do!
